# Generated by Django 4.2.30 on 2026-07-12 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 - Direct'), ('2', 'Scope 2 - Indirect (Energy)'), ('3', 'Scope 3 - Indirect (Other)')], max_length=10)),
                ('unit', models.CharField(max_length=30)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', 'activity_type'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('activity_type', models.CharField(help_text='Must match an EmissionFactor activity_type for auto-calc', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManufacturingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('activity_type', models.CharField(help_text='Must match an EmissionFactor activity_type for auto-calc', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_line', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FleetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('activity_type', models.CharField(help_text='Must match an EmissionFactor activity_type for auto-calc', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('activity_type', models.CharField(help_text='Must match an EmissionFactor activity_type for auto-calc', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_category', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('carbon_reduction_pct', 'Carbon Reduction %'), ('renewable_energy_pct', 'Renewable Energy %'), ('waste_reduction_pct', 'Waste Reduction %'), ('water_reduction_pct', 'Water Reduction %'), ('energy_efficiency', 'Energy Efficiency')], max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='%', max_length=30)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('missed', 'Missed'), ('achieved', 'Achieved')], default='on_track', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_goals', to='core.department')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('purchase', 'Purchase'), ('manufacturing', 'Manufacturing'), ('expense', 'Expense'), ('fleet', 'Fleet'), ('manual', 'Manual Entry')], max_length=20)),
                ('source_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('activity_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calculated_emissions_kgco2e', models.DecimalField(decimal_places=4, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('is_auto_calculated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_transactions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_transactions', to='core.department')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='carbon.emissionfactor')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
