# Generated by Django 4.2.30 on 2026-07-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_department_company'),
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbontransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbon_transactions', to='core.company'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='core.company'),
        ),
        migrations.AddField(
            model_name='environmentalgoal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_goals', to='core.company'),
        ),
    ]
