# Generated by Django 4.2.30 on 2026-07-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_department_company'),
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.company'),
        ),
        migrations.AddField(
            model_name='complianceissue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_issues', to='core.company'),
        ),
        migrations.AddField(
            model_name='esgpolicy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.company'),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='core.company'),
        ),
    ]
