# Generated by Django 4.2.30 on 2026-07-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_department_company'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.company'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.company'),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='core.company'),
        ),
        migrations.AddField(
            model_name='departmentscore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_scores', to='core.company'),
        ),
        migrations.AddField(
            model_name='employeebadge',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_badges', to='core.company'),
        ),
        migrations.AddField(
            model_name='employeexp',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_xps', to='core.company'),
        ),
        migrations.AddField(
            model_name='reward',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.company'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='core.company'),
        ),
    ]
