# Generated by Django 4.2.30 on 2026-07-12 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('csr', 'CSR Activity'), ('challenge', 'Challenge')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ESGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_weight', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('social_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('governance_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('auto_emission_calculation', models.BooleanField(default=True, help_text='When enabled, Carbon Transactions are auto-calculated from ERP records.')),
                ('evidence_required_for_csr', models.BooleanField(default=True, help_text='When enabled, CSR participation cannot be approved without proof file.')),
                ('badge_auto_award', models.BooleanField(default=True, help_text='When enabled, badges are auto-awarded when unlock rules are met.')),
                ('notify_compliance_issue', models.BooleanField(default=True)),
                ('notify_approval_decisions', models.BooleanField(default=True)),
                ('notify_policy_reminders', models.BooleanField(default=True)),
                ('notify_badge_unlocks', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESG Configuration',
                'verbose_name_plural': 'ESG Configuration',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='core.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
