# Generated by Django 4.2.30 on 2026-07-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_department_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esgconfiguration',
            options={'verbose_name': 'ESG Configuration', 'verbose_name_plural': 'ESG Configurations'},
        ),
        migrations.AddField(
            model_name='esgconfiguration',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.company'),
        ),
    ]
