# Generated by Django 4.2.30 on 2026-07-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_esgconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('carbon_footprint_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='CO2 footprint per unit', max_digits=10)),
                ('recyclability_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of recyclable content', max_digits=5)),
                ('sustainable_sourced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
